// Generated by CSV → questions.js Builder
window.QUESTIONS = [
  {
    id: 1,
    text: `A food borne outbreak is when you have at least __ people showing similar symptoms after eating the same food at the same location?`,
    options: [`2`, `3`, `4`, `None of these`],
    correctIndex: 0
  },
  {
    id: 2,
    text: `Which of the following is an example of a high risk population?`,
    options: [`Young children`, `Sick people`, `The elderly`, `All of these`],
    correctIndex: 3
  },
  {
    id: 3,
    text: `All foods served in the food establishment must be from approved sources such as what?`,
    options: [`Myhome`, `An unlicensed street vendor`, `A licensed food distributor`, `None of these`],
    correctIndex: 2
  },
  {
    id: 4,
    text: `Which of the following statements about the FDA is incorrect?`,
    options: [`It writes the Food Code`, `It inspects all food except meat, poultry, and eggs`, `Requires a person in charge to become a certified food protection`, `Does not require a person in charge to be on-site at all times during operating hour`],
    correctIndex: 3
  },
  {
    id: 5,
    text: `A serious food borne illness that is commonly transmitted by fecal-oral routes is caused by which virus?`,
    options: [`E. Coli`, `Yeast`, `Hepatitis A`, `Mold`],
    correctIndex: 2
  },
  {
    id: 6,
    text: `Under ideal conditions, bacteria can multiply every __`,
    options: [`20 minutes`, `40 minutes`, `90 minutes`, `Bacteria do not multiply`],
    correctIndex: 0
  },
  {
    id: 7,
    text: `What is the range of temperature for the Danger Zone?`,
    options: [`0 °F -100°F`, `41 °F -135°F`, `32 °F -212°F`, `45 °F -140°F`],
    correctIndex: 1
  },
  {
    id: 8,
    text: `Which bacteria is associated with contaminated lunch meats and grows at temperatures below 41 °F`,
    options: [`Salmonella`, `Shigella`, `Listeria`, `Bacillus Cereus`],
    correctIndex: 2
  },
  {
    id: 9,
    text: `Which parasite is associated with foodborne illnesses caused by undercooked pork?`,
    options: [`Trichinella`, `Giardia`, `Anisakis`, `Shigella`],
    correctIndex: 0
  },
  {
    id: 10,
    text: `Which bacteria is associated with foodborne illnesses caused by undercooked ground beef?`,
    options: [`Salmonella`, `Shigella`, `Staphylococcus Aureus`, `Shiga toxin producing E. Coli`],
    correctIndex: 3
  },
  {
    id: 11,
    text: `What is the main goal for controlling time and temperature?`,
    options: [`Increase the number of bacteria`, `Reduce and prevent the growth of bacteria`, `Control the acidity and moisture of the food`, `All of these`],
    correctIndex: 1
  },
  {
    id: 12,
    text: `Toxins produced by pathogens can be easily eliminated by which activity?`,
    options: [`Cooking`, `Cooling`, `Reheating`, `None of these`],
    correctIndex: 3
  },
  {
    id: 13,
    text: `Employees with a headache and a cough who come to work should be restricted to what type of duties?`,
    options: [`Prepfood`, `Servefood`, `Stockfood`, `Wash Dishes`],
    correctIndex: 2
  },
  {
    id: 14,
    text: `Getting a foodborne illness by ingesting infected particles of feces or vomit is commonly associated with which of these viruses?`,
    options: [`HIV`, `Malaria`, `Norovirus`, `Trichinella`],
    correctIndex: 2
  },
  {
    id: 15,
    text: `What must a food handler do when he or she is feeling sick?`,
    options: [`Notify your Manager`, `Hide your sickness from your Manager`, `Don't tell your manager, but take medication`, `Continue to work until you're no longer able to`],
    correctIndex: 0
  },
  {
    id: 16,
    text: `Which of the following is a common symptom of food borne illness?`,
    options: [`Vomiting`, `Diarrhea`, `Fever`, `All of these`],
    correctIndex: 3
  },
  {
    id: 17,
    text: `What should you do at work if you have a headache, cough, and a runny nose?`,
    options: [`Go to work, but should stay away from all direct food handling`, `Go to work without any restrictions from direct food handling activities`, `Not be able to work at all that day`, `Go to work and serve food`],
    correctIndex: 0
  },
  {
    id: 18,
    text: `The FDA has created a food defense program called ALERT. What part of the program includes paying attention to who is in the food facility and also conducting background checks of employees during the hiring process?`,
    options: [`Assure`, `Look`, `Employees`, `Threat`],
    correctIndex: 2
  },
  {
    id: 19,
    text: `Which of these is NOT a potential chemical hazard?`,
    options: [`Storing chemicals separately from foods`, `Spraying pesticides when food is being prepared`, `Wiping down tables with sanitizers when guests are`, `Storing chemicals in the dry food storage area`],
    correctIndex: 0
  },
  {
    id: 20,
    text: `Which of these is NOT considered a potential physical hazard?`,
    options: [`FakeNails`, `Plastic pieces from packaging`, `Cherry Pits`, `Pesticides`],
    correctIndex: 3
  },
  {
    id: 21,
    text: `Pieces of glass and strands of hair are examples of what type of hazard?`,
    options: [`Physical hazards`, `Biological hazards`, `Chemical hazards`, `Cross Contamination`],
    correctIndex: 0
  },
  {
    id: 22,
    text: `Which of the following is an example of a potential cross contamination 7`,
    options: [`Cutting raw chicken then slicing melons on the same cutting board`, `Filleting fish then cutting a chocolate cake using the same knife`, `Storing raw foods and ready-to-eat foods on the same shelf in the refrigerator`, `All of these`],
    correctIndex: 3
  },
  {
    id: 23,
    text: `Which of these is an example of PHF/TCS foods (Potentially Hazardous Food/Time Controlled for Safety)?`,
    options: [`Pizza`, `Hamburger`, `Tacos`, `All of these`],
    correctIndex: 3
  },
  {
    id: 24,
    text: `Which of these is NOT a PHF/TCS food (Potentially Hazardous Food/Time Controlled for Safety)?`,
    options: [`Fried Chicken`, `Uncooked Rice`, `Sliced Melons`, `Steak`],
    correctIndex: 1
  },
  {
    id: 25,
    text: `Which of these is an example of Ready-to-Eat foods?`,
    options: [`Banana`, `Apple`, `Muffin`, `All of these`],
    correctIndex: 3
  },
  {
    id: 26,
    text: `Which thermometer is the most widely used to take the internal temperature of food?`,
    options: [`Thermistor`, `Thermocouple`, `Bimetallic Thermometer`, `Infrared Thermometer`],
    correctIndex: 2
  },
  {
    id: 27,
    text: `Which of these is not one of the Big 6 (the most common food borne illness causes)?`,
    options: [`Salmonella Typhi`, `Shigella`, `Shiga toxin E. Coli`, `Clostridium Botulinum`],
    correctIndex: 3
  },
  {
    id: 28,
    text: `What is the correct temperature reading when calibrating a thermometer using the ice point method?`,
    options: [`32°F`, `41°F`, `0°F`, `45°F`],
    correctIndex: 0
  },
  {
    id: 29,
    text: `Raw foods dripping onto ready to eat foods is an example of what type of hazard?`,
    options: [`Physical Hazard`, `Chemical Hazard`, `Cross Contamination`, `Chemical Contamination`],
    correctIndex: 2
  },
  {
    id: 30,
    text: `When should thermometers be re-calibrated?`,
    options: [`When recently dropped`, `When used for extreme temperatures`, `When they haven't been used for long periods of time`, `All of these`],
    correctIndex: 3
  },
  {
    id: 31,
    text: `What type of hazard are we avoiding by using different cutting boards when cutting raw chicken and chopping raw vegetables?`,
    options: [`Physical Hazard`, `Cross Contamination`, `Chemical Hazard`, `Cross Contact`],
    correctIndex: 1
  },
  {
    id: 32,
    text: `Finding ice crystals on a delivery of frozen foods is a sign of what?`,
    options: [`Time and temperature abuse`, `Pest activity`, `Proper cold storage`, `Proper cooling`],
    correctIndex: 0
  },
  {
    id: 33,
    text: `Upon delivery, it is important to make sure cold, non-frozen foods such as raw meats are received at or colder`,
    options: [`0°F`, `32°F`, `41°F`, `50°F`],
    correctIndex: 2
  },
  {
    id: 34,
    text: `Upon delivery, it is important to make sure hot foods such as soups or stews are received at or hotter`,
    options: [`100°F`, `135°F`, `165°F`, `180°F`],
    correctIndex: 1
  },
  {
    id: 35,
    text: `Which of the following is NOT a proper method for thawing frozen foods?`,
    options: [`Leaving it out on the kitchen`, `Under cold, running water`, `Placing it directly from the freezer to the refrigerator`, `As part of the normal cooking process`],
    correctIndex: 0
  },
  {
    id: 36,
    text: `What is the minimum cooking temperature for ground beef?`,
    options: [`135 °F`, `145°F`, `155 °F`, `165.F`],
    correctIndex: 2
  },
  {
    id: 37,
    text: `When taking the temperature of a steak, where should you insert the thermometer?`,
    options: [`In the thickest part`, `In the thinnest part`, `At the ends`, `None of these`],
    correctIndex: 0
  },
  {
    id: 38,
    text: `What is the minimum cooking temperature for pork?`,
    options: [`135 °F`, `145 °F`, `155 °F`, `165 °F`],
    correctIndex: 1
  },
  {
    id: 39,
    text: `Failing to cook chicken to an internal cooking temperature of 165°F is what type of hazard?`,
    options: [`Physical Hazard`, `Chemical Hazard`, `Biological Hazard`, `Cross Contamination`],
    correctIndex: 2
  },
  {
    id: 40,
    text: `Which of these examples is improper when serving food?`,
    options: [`Using tongs to serve Ready-to-Eat`, `Holding the dishes from the bottom`, `Using the same utensil for different kinds of food`, `Holding utensils by the handle`],
    correctIndex: 2
  },
  {
    id: 41,
    text: `What is the maximum amount of TOTAL time {including transit time, receiving, prep, etc) TCS foods can be in the temperature danger zone?`,
    options: [`2 hours`, `3 hours`, `4 hours`, `6 hours`],
    correctIndex: 2
  },
  {
    id: 42,
    text: `The 2 stage cooling process involves cooling hot foods to 70°F within 2 hours or less and then from 70°F to 41°F in ___ hours or less?`,
    options: [`6`, `3`, `4`, `2`],
    correctIndex: 2
  },
  {
    id: 43,
    text: `Proper cooling must take place within a total of ____ hours or less.`,
    options: [`2`, `4`, `6`, `8`],
    correctIndex: 2
  },
  {
    id: 44,
    text: `Which of these is NOT an acceptable way to cool foods?`,
    options: [`Place foods in an ice bath`, `Cut foods into smaller pieces`, `Use shallow pans`, `At room temperature`],
    correctIndex: 3
  },
  {
    id: 45,
    text: `Where should ready-to-eat foods such as pies and other desserts be stored in the cooler, to prevent cross-contamination?`,
    options: [`Top shelf above raw foods`, `Middle shelf`, `Bottom shelf below raw foods`, `Anywhere there is space`],
    correctIndex: 0
  },
  {
    id: 46,
    text: `What does First In First Out mean?`,
    options: [`Foods with the latest expiration date should be used first`, `Foods should be used in any order`, `Foods with approaching expiration dates should be used first`, `None of these`],
    correctIndex: 2
  },
  {
    id: 47,
    text: `Food in dry storage mus t be ___ inches off the ground.`,
    options: [`3`, `4`, `6`, `12`],
    correctIndex: 2
  },
  {
    id: 48,
    text: `There are __ major food allergens.`,
    options: [`6`, `9`, `12`, `16`],
    correctIndex: 1
  },
  {
    id: 49,
    text: `Which of these is not considered a major food allergen?`,
    options: [`Soy products`, `Dairy Products`, `Fish`, `Rice Products`],
    correctIndex: 3
  },
  {
    id: 50,
    text: `Which of these is not considered a major food allergen?`,
    options: [`Beef`, `Eggs`, `Shellfish`, `Wheat`],
    correctIndex: 0
  },
  {
    id: 51,
    text: `Of the following, what is a likely source for food contamination?`,
    options: [`Sick employee sneezes on the food`, `Cooking chicken to the required internal correct temperature`, `Using gloves and tongs to serve ready-to-eat foods`, `Chewing gum in the break room during break`],
    correctIndex: 0
  },
  {
    id: 52,
    text: `When must you wash your hands?`,
    options: [`After touching your cell phone`, `After using the restroom`, `Aftereating`, `All of these`],
    correctIndex: 3
  },
  {
    id: 53,
    text: `Which of these is required at a handwashing sink?`,
    options: [`Soap`, `Cold water only`, `Cloth towel for drying`, `Sanitizer`],
    correctIndex: 0
  },
  {
    id: 54,
    text: `For food service employees, what is the TOTAL minimum time requirement for washing hands?`,
    options: [`10 seconds`, `15 seconds`, `20 seconds`, `All of these`],
    correctIndex: 2
  },
  {
    id: 55,
    text: `Which of these is NOT an acceptable means to dry hands?`,
    options: [`Paper Towel`, `Cloth Towel`, `AirDry`, `Hot Air Blower`],
    correctIndex: 1
  },
  {
    id: 56,
    text: `Where is handwashing permitted?`,
    options: [`In any available sink or faucet available`, `Only in designated hand washing stations`, `In the dishwashing sink`, `All of these`],
    correctIndex: 1
  },
  {
    id: 57,
    text: `Which of the following is a requirement at a handwashing station?`,
    options: [`Soap`, `Signage about handwashing requirement`, `A means to dry hands such as a paper towel or air blower`, `All of these`],
    correctIndex: 3
  },
  {
    id: 58,
    text: `When must you wash your hands?`,
    options: [`Before you start working with food`, `After using the restroom`, `After taking out the garbage`, `All of these`],
    correctIndex: 3
  },
  {
    id: 59,
    text: `After washing your hands in the restroom, what must you do after entering the food prep area?`,
    options: [`Put on clean gloves`, `Sanitize your hands with hand sanitizers`, `Wash your hands again before working with food`, `None of these`],
    correctIndex: 2
  },
  {
    id: 60,
    text: `When are you required to change gloves?`,
    options: [`Between tasks`, `When the glove tears`, `After 4 hours`, `All of these`],
    correctIndex: 3
  },
  {
    id: 61,
    text: `Which of the following behaviors should employees refrain from doing when preparing food?`,
    options: [`Eat and drink`, `Smoke`, `Use their cellphone`, `All of these`],
    correctIndex: 3
  },
  {
    id: 62,
    text: `What should employees do to show good personal hygiene?`,
    options: [`Take a shower before coming to work`, `Look presentable with clean clothes and shoes`, `Wear hair restraints to prevent hair from getting onto food`, `All of these`],
    correctIndex: 3
  },
  {
    id: 63,
    text: `Which of the following should food handlers do to prevent contamination?`,
    options: [`Not wear false nails`, `Keep their nails short and clean`, `Not have nail polish on their nails`, `All of these`],
    correctIndex: 3
  },
  {
    id: 64,
    text: `What must food handlers do before putting on a new pair of gloves?`,
    options: [`Wash their hands`, `Use hand sanitizer`, `Shower`, `Shower`],
    correctIndex: 0
  },
  {
    id: 65,
    text: `Gloves must be changed at least once every __ hours?`,
    options: [`6`, `3`, `4`, `2`],
    correctIndex: 2
  },
  {
    id: 66,
    text: `Which of the following is an example of improper storage in the walk-in cooler?`,
    options: [`lightly covered, cooked ribs is cooling on the top shelf`, `raw chicken is stored above lunch meats`, `cheese platter is stored in a closed plastic container above raw`, `frozen chicken is thawing in a pan on the bottom shelf`],
    correctIndex: 1
  },
  {
    id: 67,
    text: `Which of the following is the correct order to properly clean and sanitize food contact surfaces?`,
    options: [`Scraping, washing, sanitizing, rinsing, air dry`, `Scraping, washing, rinsing, sanitizing, air drying`, `Scraping, sanitizing, rinsing, washing, towel drying`, `Scraping, washing, sanitizing, rinsing, towel drying`],
    correctIndex: 1
  },
  {
    id: 68,
    text: `What does the process of sanitizing mean?`,
    options: [`Removing dirt, soil, and chemicals`, `Allowing it to air dry`, `Killing or reducing pathogens to safe levels`, `All of these`],
    correctIndex: 2
  },
  {
    id: 69,
    text: `When a health inspector arrives, you should do all of the following except`,
    options: [`ask for identification`, `allow inspection without advance notice`, `offer him a gift in exchange for a clean inspection report`, `ask questions if something is not clear`],
    correctIndex: 2
  },
  {
    id: 70,
    text: `All food contact surfaces currently in use including equipment and utensils must be washed and sanitized at least once every ___ hours?`,
    options: [`2`, `4`, `6`, `3`],
    correctIndex: 1
  },
  {
    id: 71,
    text: `What do test kits measure in sanitizing solution?`,
    options: [`Concentration`, `Temperature`, `Color`, `Water Hardness`],
    correctIndex: 0
  },
  {
    id: 72,
    text: `All of the following should be rejected upon delivery EXCEPT`,
    options: [`shellfish that have shellstock ID`, `packages with missing labels`, `cans that are rusty`, `NA`],
    correctIndex: 0
  },
  {
    id: 73,
    text: `All food delivery vehicles should`,
    options: [`have proper signage on the doors`, ``, `have clean and sanitary conditions`, `NA`],
    correctIndex: 2
  },
  {
    id: 74,
    text: `All of the following are true for canned goods EXCEPT`,
    options: [`must be checked for leaks, dents, rust, missing labels`, `must be purchased at the lowest price possible`, `must be stored according to FIFO`, `NA`],
    correctIndex: 1
  },
  {
    id: 75,
    text: `First In, First Out" (FIFO) refers to the safe food handling practice of`,
    options: [`using products that were just received`, `using older products that were received first`, `using products that are expired`, `NA`],
    correctIndex: 1
  },
  {
    id: 76,
    text: `Which of the following is a TCS food?`,
    options: [`an unopened UHT coffee creamer`, `a loaf of bread`, `sliced melons`, `NA`],
    correctIndex: 2
  },
  {
    id: 77,
    text: `Which container is preferred to hold leftover spaghetti sauce in the cooler?`,
    options: [`covered food pan`, `uncovered plastic container`, `copper pot`, `NA`],
    correctIndex: 0
  },
  {
    id: 78,
    text: `What is the primary problem with cutting raw foods together on the same cutting board with cooked foods?`,
    options: [`physical contamination`, `cross-contamination`, `cross-connection`, `NA`],
    correctIndex: 1
  },
  {
    id: 79,
    text: `What is the BEST way to prevent foodborne illnesses?`,
    options: [`wearing a hair net`, `don't eat, drink or smoke while preparing food`, `frequent and effective handwashing`, `NA`],
    correctIndex: 2
  },
  {
    id: 80,
    text: `Which of the following is a safe food service practice?`,
    options: [`thawing chicken in warm water`, `putting a large pot of soup into shallow pans for cooling`, `using the same spoon to add peanuts and granola topping on ice cream`, `NA`],
    correctIndex: 1
  },
  {
    id: 81,
    text: `Where can food handlers smoke or eat?`,
    options: [`in food storage area`, `in designated areas`, `in the dishwashing area`, `NA`],
    correctIndex: 1
  },
  {
    id: 82,
    text: `Date marking is necessary for ready-to-eat or prepared TCS foods if they will be kept for longer than:`,
    options: [`12 hours`, `24 hours`, `7 days`, `NA`],
    correctIndex: 1
  },
  {
    id: 83,
    text: `Which action DOES NOT require food handlers to wash their hands and change gloves in order to prevent contamination?`,
    options: [`after checking your phone`, `after using the bathroom`, `before taking out the trash`, `NA`],
    correctIndex: 2
  },
  {
    id: 84,
    text: `Before raw fruits and vegetables are cooked or served, they should be thoroughly washed with`,
    options: [`vinegar`, `potable water`, `non-potable water`, `NA`],
    correctIndex: 1
  },
  {
    id: 85,
    text: `What is the best method to check the temperature of food on a buffet line?`,
    options: [`make sure the thermostat is checked every 6`, `check to see that steam is rising from the hot food`, `insert a thermometer into the food`, `NA`],
    correctIndex: 2
  },
  {
    id: 86,
    text: `Machine dishwashing requires all of the following EXCEPT`,
    options: [`routine checking for clogged spray nozzles or mineral deposit build`, `sanitizing temperature of at least 180°F`, `sanitizing temperature of at least 180°F`, `NA`],
    correctIndex: 2
  },
  {
    id: 87,
    text: `Wiping cloths used for wiping counters and should be`,
    options: [`stored in hot water`, `stored in a sanitizing solution`, `washed in the dishwasher`, `NA`],
    correctIndex: 1
  },
  {
    id: 88,
    text: `Chemical sanitizing solutions`,
    options: [`should have its concentration checked with a test`, `should only be used when hot water is not available`, `do not need to be properly labelled`, `NA`],
    correctIndex: 0
  },
  {
    id: 89,
    text: `Which chemical is not an approved sanitizing agent:`,
    options: [`chlorine`, `delimer`, `iodine`, `NA`],
    correctIndex: 1
  },
  {
    id: 90,
    text: `When cleaning and sanitizing electrical appliances, what should be done first?`,
    options: [`use a wet cloth to wipe down the exterior surfaces`, `wash, rinse and sanitize the food contact surfaces only`, `disconnect the power`, `NA`],
    correctIndex: 2
  },
  {
    id: 91,
    text: `Responsibilities of a food manager include the following EXCEPT:`,
    options: [`Keeping a log of employee health history`, `Training only cooking staff regarding dishes with food allergens`, `Making sure food is delivered and received during non-busy hours of the restaurant`, `NA`],
    correctIndex: 1
  },
  {
    id: 92,
    text: `Using detergents for cleaning food equipment allows:`,
    options: [`Dirt and bacteria to be washed`, `Less sanitizing solution to be used`, `The sanitizing process to be skipped`, `NA`],
    correctIndex: 0
  },
  {
    id: 93,
    text: `Drinking liquids is permitted while working under the following conditions:`,
    options: [`The drink is covered with a lid and can be consumed through a straw`, `Any container as long it is away from the food preparation area`, `Through a bottle with the lid closed when not being consumed`, `NA`],
    correctIndex: 0
  },
  {
    id: 94,
    text: `What do bacteria need in order to grow?`,
    options: [`Heat and air`, `Water and protein`, `Acid and sugar`, `NA`],
    correctIndex: 1
  },
  {
    id: 95,
    text: `When a food employee has an infected cut or burn, what should they know?`,
    options: [`They can continue to work with no restrictions`, `The infected area can contain bacteria that can cause food borne illness`, `They can continue to work by wearing gloves`, `NA`],
    correctIndex: 1
  },
  {
    id: 96,
    text: `The best way to train employees and kitchen staff is through`,
    options: [`written memos`, `clear verbal instructions`, `live demonstration`, `NA`],
    correctIndex: 2
  },
  {
    id: 97,
    text: `Smoking and eating is not permitted in the food prep area`,
    options: [`unless the food handler washes their hands before and after`, `because other kitchen staff may not like it`, `because of possible contamination by the food handler through saliva transfer`, `NA`],
    correctIndex: 2
  },
  {
    id: 98,
    text: `Before manually washing dishes in the 3 compartment sink, the first thing that needs to be done is to`,
    options: [`add clean water to the first and second`, `clean and sanitize all 3 compartments of the sink`, `add detergent to the first compartment`, `NA`],
    correctIndex: 1
  },
  {
    id: 99,
    text: `Which of the following statements regarding dumpsters and recyclables is FALSE`,
    options: [`they should be located as far away from the building as local regulations permit`, `they should be clean and tightly covered`, `they can overflow as long as they are regularly cleaned`, `NA`],
    correctIndex: 2
  },
  {
    id: 100,
    text: `Which of the following is correct regarding food allergens?`,
    options: [`They come from harmful bacteria`, `They cannot be eliminated or cooked out`, `A variance is required when serving foods with food allergens`, `NA`],
    correctIndex: 1
  },
  {
    id: 101,
    text: `Which of the following statements regarding cleaners is FALSE`,
    options: [`abrasive cleaners remove relatively heavy amounts of dirt, stains, and hard water deposits by scraping`, `degreasers dissolve grease and oil`, `detergents are cleaners that clean by sanitizing surfaces`, `NA`],
    correctIndex: 2
  },
  {
    id: 102,
    text: `Pests are growing in numbers. Which step can prevent the problem from getting worse?`,
    options: [`Clean up any leftover food on tables and floors`, `Open windows and doors during business hours`, `Leave trash cans uncovered`, `NA`],
    correctIndex: 0
  },
  {
    id: 103,
    text: `The 2-stage cooling process allows for a maximum of how many hours in the temperature danger zone?`,
    options: [`3 hours`, `4 hours`, `6 hours`, `NA`],
    correctIndex: 2
  },
  {
    id: 104,
    text: `A bag of flour in the storage room`,
    options: [`can be placed on a clean, dry floor`, `should be placed on a shelf 6 inches from the floor and wall`, `should be placed on a shelf 12 inches from the floor and wall`, `NA`],
    correctIndex: 1
  },
  {
    id: 105,
    text: `Toxic metal poisoning is caused when certain metals`,
    options: [`are heated on high heat and toxins are released into the foods`, `like gold, silver, and aluminum are mixed with acidic foods and toxins are produced`, `like copper, brass and tin are mixed with acidic foods and toxins are produced`, `NA`],
    correctIndex: 2
  },
  {
    id: 106,
    text: `When packaging food for sale in your restaurant, which of the following is NOT required?`,
    options: [`date the food was made or sell by date`, `nutrition information`, `ingredient list`, `NA`],
    correctIndex: 1
  },
  {
    id: 107,
    text: `A food establishment that has a sewage backup on its premise must close`,
    options: [`immediately`, `within 4 hours`, `within 6 hours`, `NA`],
    correctIndex: 0
  },
  {
    id: 108,
    text: `When receiving frozen foods, reject shipments when`,
    options: [`meats are colder than O degrees Fahrenheit`, `the expiration date is valid`, `there is presence of large ice crystals around the packaging`, `NA`],
    correctIndex: 2
  },
  {
    id: 109,
    text: `What items can customers re-use in a buffet line?`,
    options: [`tableware such as forks, spoons and knives`, `plates`, `cups and glasses`, `NA`],
    correctIndex: 2
  },
  {
    id: 110,
    text: `Which of these is a UHT (Ultra High Temperature) food?`,
    options: [`canned tuna`, `single use ketchup`, `some types of coffee creamers`, `NA`],
    correctIndex: 2
  },
  {
    id: 111,
    text: `A severe allergic reaction to foods is called`,
    options: [`strep throat`, `anaphylaxis`, `food poisoning`, `NA`],
    correctIndex: 1
  }
];
