// questions.js
// Expand to 100 questions (A–D only). correctIndex is 0-based.

// Generated by CSV → questions.js Builder
window.QUESTIONS = [
  {
    id: 1,
    text: `A food borne outbreak is when you have at least __ people showing similar symptoms after eating the same food at the same location?`,
    options: [`2`, `3`, `4`, `None of these`],
    correctIndex: 0
  },
  {
    id: 2,
    text: `Which of the following is an example of a high risk population?`,
    options: [`Young children`, `Sick people`, `The elderly`, `All of these`],
    correctIndex: 3
  },
  {
    id: 3,
    text: `All foods served in the food establishment must be from approved sources such as what?`,
    options: [`Myhome`, `An unlicensed street vendor`, `A licensed food distributor`, `None of these`],
    correctIndex: 1
  },
  {
    id: 4,
    text: `Which of the following statements about the FDA is incorrect?`,
    options: [`It writes the Food Code`, `It inspects all food except meat, poultry, and eggs`, `Requires a person in charge to become a certified food protection`, `Does not require a person in charge to be on-site at all times during operating hour`],
    correctIndex: 3
  }
];

// TIP: To add more, copy ↓ and update id/text/options/correctIndex
// { id: 5, text: "Your question...", options: ["A","B","C","D"], correctIndex: 1 },
